name: Build and Push

on: 
    push:
        branches:
            - main
            - master
    workflow_dispatch:
        inputs: {}

jobs:
    build:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - name: Build the Docker image
              run: make build
