on:
    push:
        branches:
            - main
    workflow_dispatch:  # Magic line to enable manual workflow runs with the "Run workflow" button
        inputs: {} 

jobs:
    print_hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world
              run: echo "Hello world!"
